
export const catData = [
  { "Nhom": "bacnghe", "NoiDung": "07/07", "GiaTri": "07/07" },
  { "Nhom": "bacnghe", "NoiDung": "06/07", "GiaTri": "06/07" },
  { "Nhom": "bacnghe", "NoiDung": "05/07", "GiaTri": "05/07" },
  { "Nhom": "bacnghe", "NoiDung": "04/07", "GiaTri": "04/07" },
  { "Nhom": "bacnghe", "NoiDung": "03/07", "GiaTri": "03/07" },
  { "Nhom": "bacnghe", "NoiDung": "02/07", "GiaTri": "02/07" },
  { "Nhom": "bacnghe", "NoiDung": "01/07", "GiaTri": "01/07" },

  { "Nhom": "congsuat", "NoiDung": "100", "GiaTri": 100 },
  { "Nhom": "congsuat", "NoiDung": "180", "GiaTri": 180 },
  { "Nhom": "congsuat", "NoiDung": "160", "GiaTri": 160 },
  { "Nhom": "congsuat", "NoiDung": "250", "GiaTri": 250 },
  { "Nhom": "congsuat", "NoiDung": "112.5", "GiaTri": 112.5 },
  { "Nhom": "congsuat", "NoiDung": "150", "GiaTri": 150 },
  { "Nhom": "congsuat", "NoiDung": "50", "GiaTri": 50 },
  { "Nhom": "congsuat", "NoiDung": "560", "GiaTri": 560 },
  { "Nhom": "congsuat", "NoiDung": "1000", "GiaTri": 1000 },
  { "Nhom": "congsuat", "NoiDung": "75", "GiaTri": 75 },
  { "Nhom": "congsuat", "NoiDung": "25", "GiaTri": 25 },
  { "Nhom": "congsuat", "NoiDung": "400", "GiaTri": 400 },

  { "Nhom": "chucdanh", "NoiDung": "Phụ trách phòng", "GiaTri": "Phụ trách phòng" },
  { "Nhom": "chucdanh", "NoiDung": "Phó Trưởng Phòng", "GiaTri": "Phó Trưởng Phòng" },
  { "Nhom": "chucdanh", "NoiDung": "Trưởng phòng", "GiaTri": "Trưởng phòng" },
  { "Nhom": "chucdanh", "NoiDung": "Phó Giám đốc", "GiaTri": "Phó Giám đốc" },
  { "Nhom": "chucdanh", "NoiDung": "Giám Đốc", "GiaTri": "Giám Đốc" },

  { "Nhom": "DapAn", "NoiDung": "E", "GiaTri": "E" },
  { "Nhom": "DapAn", "NoiDung": "D", "GiaTri": "D" },
  { "Nhom": "DapAn", "NoiDung": "A", "GiaTri": "A" },
  { "Nhom": "DapAn", "NoiDung": "C", "GiaTri": "C" },
  { "Nhom": "DapAn", "NoiDung": "B", "GiaTri": "B" },

  { "Nhom": "DVT", "NoiDung": "Phần", "GiaTri": "P" },
  { "Nhom": "DVT", "NoiDung": "Lốc", "GiaTri": "L" },
  { "Nhom": "DVT", "NoiDung": "Tuýp", "GiaTri": "T" },
  { "Nhom": "DVT", "NoiDung": "Cục", "GiaTri": "C" },
  { "Nhom": "DVT", "NoiDung": "Thùng", "GiaTri": "T" },
  { "Nhom": "DVT", "NoiDung": "Chục", "GiaTri": "C" },
  { "Nhom": "DVT", "NoiDung": "Bó", "GiaTri": "B" },
  { "Nhom": "DVT", "NoiDung": "Miếng", "GiaTri": "M" },
  { "Nhom": "DVT", "NoiDung": "Quả", "GiaTri": "Q" },
  { "Nhom": "DVT", "NoiDung": "Kg", "GiaTri": "K" },
  { "Nhom": "DVT", "NoiDung": "Bịch", "GiaTri": "B" },
  { "Nhom": "DVT", "NoiDung": "Bộ", "GiaTri": "B" },
  { "Nhom": "DVT", "NoiDung": "Cái", "GiaTri": "C" },
  { "Nhom": "DVT", "NoiDung": "Chai", "GiaTri": "C" },
  { "Nhom": "DVT", "NoiDung": "Dĩa", "GiaTri": "D" },
  { "Nhom": "DVT", "NoiDung": "Gói", "GiaTri": "G" },
  { "Nhom": "DVT", "NoiDung": "Hộp", "GiaTri": "H" },
  { "Nhom": "DVT", "NoiDung": "Lọ", "GiaTri": "L" },
  { "Nhom": "DVT", "NoiDung": "Lon", "GiaTri": "L" },
  { "Nhom": "DVT", "NoiDung": "Ly", "GiaTri": "L" },
  { "Nhom": "DVT", "NoiDung": "Lít", "GiaTri": "L" },
  { "Nhom": "DVT", "NoiDung": "Vỉ", "GiaTri": "V" },
  { "Nhom": "DVT", "NoiDung": "Viên", "GiaTri": "V" },

  { "Nhom": "GhiChuMon", "NoiDung": "Không đường", "GiaTri": 6 },
  { "Nhom": "GhiChuMon", "NoiDung": "Thêm ngọt", "GiaTri": 5 },
  { "Nhom": "GhiChuMon", "NoiDung": "Thêm sữa", "GiaTri": 4 },
  { "Nhom": "GhiChuMon", "NoiDung": "Ít béo", "GiaTri": 3 },
  { "Nhom": "GhiChuMon", "NoiDung": "Ít đá", "GiaTri": 2 },
  { "Nhom": "GhiChuMon", "NoiDung": "Ít ngọt", "GiaTri": 1 },
  { "Nhom": "GhiChuMon", "NoiDung": "1 phần", "GiaTri": 7 },
  { "Nhom": "GhiChuMon", "NoiDung": "2 phần", "GiaTri": 8 },
  { "Nhom": "GhiChuMon", "NoiDung": "3 phần", "GiaTri": 9 },
  { "Nhom": "GhiChuMon", "NoiDung": "Tất cả", "GiaTri": 10 },

  { "Nhom": "GioiTinh", "NoiDung": "Nam", "GiaTri": 1 },
  { "Nhom": "GioiTinh", "NoiDung": "Không xác định", "GiaTri": 0 },
  { "Nhom": "GioiTinh", "NoiDung": "Nữ", "GiaTri": 0 },

  { "Nhom": "KhenThuong", "NoiDung": "Công ty", "GiaTri": 1 },
  { "Nhom": "KhenThuong", "NoiDung": "Đảng bộ Công ty", "GiaTri": 2 },
  { "Nhom": "KhenThuong", "NoiDung": "Điện lực", "GiaTri": 3 },
  { "Nhom": "KhenThuong", "NoiDung": "Tổng Công ty Điện lực Miền Nam", "GiaTri": 4 },
  { "Nhom": "KhenThuong", "NoiDung": "Tập đoàn Điện lực Việt Nam", "GiaTri": 5 },
  { "Nhom": "KhenThuong", "NoiDung": "UBND huyện", "GiaTri": 6 },
  { "Nhom": "KhenThuong", "NoiDung": "UBND tỉnh", "GiaTri": 7 },
  { "Nhom": "KhenThuong", "NoiDung": "Bộ Công thương", "GiaTri": 8 },
  { "Nhom": "KhenThuong", "NoiDung": "Thủ tướng Chính phủ", "GiaTri": 9 },
  { "Nhom": "KhuVuc", "NoiDung": "Khu A", "GiaTri": "Khu A" },
  { "Nhom": "KhuVuc", "NoiDung": "Khu B", "GiaTri": "Khu B" },
  { "Nhom": "KhuVuc", "NoiDung": "Khu C", "GiaTri": "Khu C" },
  { "Nhom": "KhuVuc", "NoiDung": "Khu D", "GiaTri": "Khu D" },
  { "Nhom": "KhuVuc", "NoiDung": "Khu E", "GiaTri": "Khu E" },
  { "Nhom": "LoaiDanhBa", "NoiDung": "Khách hàng", "GiaTri": 3 },
  { "Nhom": "LoaiDanhBa", "NoiDung": "Nhân viên giao hàng", "GiaTri": 2 },
  { "Nhom": "LoaiDanhBa", "NoiDung": "Nhà cung cấp", "GiaTri": 1 },
  { "Nhom": "pha", "NoiDung": "1", "GiaTri": 1 },
  { "Nhom": "pha", "NoiDung": "3", "GiaTri": 3 },
  { "Nhom": "pha", "NoiDung": "C", "GiaTri": "C" },
  { "Nhom": "pha", "NoiDung": "B", "GiaTri": "B" },
  { "Nhom": "pha", "NoiDung": "A", "GiaTri": "A" },
  { "Nhom": "PhongBan", "NoiDung": "Đội QLVH ĐD&TBA", "GiaTri": 1 },
  { "Nhom": "PhongBan", "NoiDung": "Phòng Kinh doanh", "GiaTri": 3 },
  { "Nhom": "PhongBan", "NoiDung": "Phòng Kế hoạch - Kỹ thuật", "GiaTri": 2 },
  { "Nhom": "PhongBan", "NoiDung": "Phòng Tài chính Kế toán", "GiaTri": 4 },
  { "Nhom": "PhongBan", "NoiDung": "Phòng Tổng Hợp", "GiaTri": 5 },
  { "Nhom": "quiz", "NoiDung": "An Toàn Điện", "GiaTri": "An Toàn Điện" },
  { "Nhom": "quiz", "NoiDung": "Thi nâng bậc", "GiaTri": "Thi nâng bậc" },
  { "Nhom": "quiz", "NoiDung": "E-Learning", "GiaTri": "E-Learning" },
  { "Nhom": "SIZE", "NoiDung": "XXL", "GiaTri": 5000 },
  { "Nhom": "SIZE", "NoiDung": "M", "GiaTri": "M" },
  { "Nhom": "SIZE", "NoiDung": "S", "GiaTri": "S" },
  { "Nhom": "SIZE", "NoiDung": "XL", "GiaTri": "XL" },
  { "Nhom": "SIZE", "NoiDung": "XXL", "GiaTri": "XXL" },
  { "Nhom": "SIZE", "NoiDung": "XXL", "GiaTri": 5000 },
  { "Nhom": "SIZE", "NoiDung": "M", "GiaTri": "M" },
  { "Nhom": "SIZE", "NoiDung": "S", "GiaTri": "S" },
  { "Nhom": "SIZE", "NoiDung": "XL", "GiaTri": "XL" },
  { "Nhom": "SIZE", "NoiDung": "XXL", "GiaTri": "XXL" },
  { "Nhom": "Social", "NoiDung": "Zalo", "GiaTri": 3 },
  { "Nhom": "Social", "NoiDung": "Facebook", "GiaTri": 2 },
  { "Nhom": "Social", "NoiDung": "Google", "GiaTri": 1 },
  { "Nhom": "sohuu", "NoiDung": "DL", "GiaTri": "DL" },
  { "Nhom": "sohuu", "NoiDung": "KH", "GiaTri": "KH" },
  { "Nhom": "SoLy", "NoiDung": "Tất cả", "GiaTri": 4 },
  { "Nhom": "SoLy", "NoiDung": "1 ly", "GiaTri": 1 },
  { "Nhom": "SoLy", "NoiDung": "3 ly", "GiaTri": 3 },
  { "Nhom": "SoLy", "NoiDung": "2 ly", "GiaTri": 2 },
  { "Nhom": "SoLy", "NoiDung": "Tất cả", "GiaTri": 4 },
  { "Nhom": "SoLy", "NoiDung": "1 ly", "GiaTri": 1 },
  { "Nhom": "SoLy", "NoiDung": "3 ly", "GiaTri": 3 },
  { "Nhom": "SoLy", "NoiDung": "2 ly", "GiaTri": 2 },
  { "Nhom": "tapthe", "NoiDung": "Đội Quản lý vận hành đường dây và trạm biến áp", "GiaTri": "Đội Quản lý vận hành đường dây và trạm biến áp" },
  { "Nhom": "tapthe", "NoiDung": "Tổ Hành chính - Quản trị", "GiaTri": "Tổ Hành chính - Quản trị" },
  { "Nhom": "tapthe", "NoiDung": "Phòng Tài chính Kế toán", "GiaTri": "Phòng Tài chính Kế toán" },
  { "Nhom": "tapthe", "NoiDung": "Phòng Tổng hợp", "GiaTri": "Phòng Tổng hợp" },
  { "Nhom": "tapthe", "NoiDung": "Phòng Kế hoạch - Kỹ thuật", "GiaTri": "Phòng Kế hoạch - Kỹ thuật" },
  { "Nhom": "tapthe", "NoiDung": "Tổ Treo tháo điện kế", "GiaTri": "Tổ Treo tháo điện kế" },
  { "Nhom": "tapthe", "NoiDung": "Tổ Kiểm tra sử dụng điện", "GiaTri": "Tổ Kiểm tra sử dụng điện" },
  { "Nhom": "tapthe", "NoiDung": "Tổ Ghi điện", "GiaTri": "Tổ Ghi điện" },
  { "Nhom": "tapthe", "NoiDung": "Tổ Thu ngân", "GiaTri": "Tổ Thu ngân" },
  { "Nhom": "tapthe", "NoiDung": "Tổ Dịch vụ khách hàng", "GiaTri": "Tổ Dịch vụ khách hàng" },
  { "Nhom": "tapthe", "NoiDung": "Tổ Điều độ", "GiaTri": "Tổ Điều độ" },
  { "Nhom": "tapthe", "NoiDung": "Tổ Kế hoạch - Kỹ thuật", "GiaTri": "Tổ Kế hoạch - Kỹ thuật" },
  { "Nhom": "tapthe", "NoiDung": "Tổ Kỹ thuật an toàn", "GiaTri": "Tổ Kỹ thuật an toàn" },
  { "Nhom": "tapthe", "NoiDung": "Tổ Vật tư", "GiaTri": "Tổ Vật tư" },
  { "Nhom": "tapthe", "NoiDung": "Tổ Quản lý kỹ thuật", "GiaTri": "Tổ Quản lý kỹ thuật" },
  { "Nhom": "tapthe", "NoiDung": "Tổ trực Trung tâm", "GiaTri": "Tổ trực Trung tâm" },
  { "Nhom": "tapthe", "NoiDung": "Tổ trực Xuân Hưng", "GiaTri": "Tổ trực Xuân Hưng" },
  { "Nhom": "TiepXuc", "NoiDung": "Cách xa hơn 2m", "GiaTri": 9 },
  { "Nhom": "TiepXuc", "NoiDung": "Sát khuẩn sau tiếp xúc", "GiaTri": 8 },
  { "Nhom": "TiepXuc", "NoiDung": "Cách 2m", "GiaTri": 7 },
  { "Nhom": "TiepXuc", "NoiDung": "Cách 1m", "GiaTri": 6 },
  { "Nhom": "TiepXuc", "NoiDung": "Mang kính chắn", "GiaTri": 5 },
  { "Nhom": "TiepXuc", "NoiDung": "Mang khẩu trang", "GiaTri": 3 },
  { "Nhom": "TiepXuc", "NoiDung": "Ngồi", "GiaTri": 2 },
  { "Nhom": "TiepXuc", "NoiDung": "Đứng", "GiaTri": 1 },
  { "Nhom": "Tuyen", "NoiDung": "478-Xuân Hưng", "GiaTri": "478-Xuân Hưng" },
  { "Nhom": "Tuyen", "NoiDung": "479-Gia Ui", "GiaTri": 479 },
  { "Nhom": "Tuyen", "NoiDung": "477-Xuân Phú", "GiaTri": 477 },
  { "Nhom": "Tuyen", "NoiDung": "476-Xuân Hòa", "GiaTri": 476 },
  { "Nhom": "Tuyen", "NoiDung": "475-Sông Ray", "GiaTri": 475 },
  { "Nhom": "Tuyen", "NoiDung": "474-Dona", "GiaTri": 474 },
  { "Nhom": "Tuyen", "NoiDung": "473-Xuân Trường", "GiaTri": 473 },
  { "Nhom": "Tuyen", "NoiDung": "472-Minh Khai", "GiaTri": 472 },
  { "Nhom": "Tuyen", "NoiDung": "471-Suối Cao", "GiaTri": 471 },
  { "Nhom": "Tuyen", "NoiDung": "480-Xuân Bắc", "GiaTri": 480 },
  { "Nhom": "ThuChi", "NoiDung": "Thu nhập ngoài", "GiaTri": "Lương ngoài" },
  { "Nhom": "ThuChi", "NoiDung": "Thu nhập chính", "GiaTri": "Lương chính" },
  { "Nhom": "ThuChi", "NoiDung": "Lãng phí", "GiaTri": 6 },
  { "Nhom": "ThuChi", "NoiDung": "Tiết kiệm", "GiaTri": 2 },
  { "Nhom": "ThuChi", "NoiDung": "Thiết yếu", "GiaTri": 1 },
  { "Nhom": "ThuChi", "NoiDung": "Từ thiện", "GiaTri": 5 },
  { "Nhom": "ThuChi", "NoiDung": "Đầu tư", "GiaTri": 4 },
  { "Nhom": "TrangThai", "NoiDung": "Đã xong", "GiaTri": 2 },
  { "Nhom": "TrangThai", "NoiDung": "Đang", "GiaTri": 1 },
  { "Nhom": "TrangThai", "NoiDung": "Chưa", "GiaTri": 0 },
  { "Nhom": "DoiTuongAT", "NoiDung": "Văn hóa doanh nghiệp", "GiaTri": 6 },
  { "Nhom": "DoiTuongAT", "NoiDung": "Vật tư", "GiaTri": 7 },
  { "Nhom": "DoiTuongAT", "NoiDung": "KT lưới điện bậc 2", "GiaTri": 8 },
  { "Nhom": "DoiTuongAT", "NoiDung": "KT lưới điện bậc 3", "GiaTri": 9 },
  { "Nhom": "DoiTuongAT", "NoiDung": "KT lưới điện bậc 4", "GiaTri": 10 },
  { "Nhom": "DoiTuongAT", "NoiDung": "KT lưới điện bậc 5", "GiaTri": 11 },
  { "Nhom": "DoiTuongAT", "NoiDung": "KT lưới điện bậc 6", "GiaTri": 12 },
  { "Nhom": "DoiTuongAT", "NoiDung": "KT lưới điện bậc 7", "GiaTri": 13 },
  { "Nhom": "DoiTuongAT", "NoiDung": "Quản lý sửa chữa lưới 2", "GiaTri": 14 },
  { "Nhom": "DoiTuongAT", "NoiDung": "Quản lý sửa chữa lưới 3", "GiaTri": 15 },
  { "Nhom": "DoiTuongAT", "NoiDung": "Quản lý sửa chữa lưới 4", "GiaTri": 16 },
  { "Nhom": "DoiTuongAT", "NoiDung": "Quản lý sửa chữa lưới 5", "GiaTri": 17 },
  { "Nhom": "DoiTuongAT", "NoiDung": "Quản lý sửa chữa lưới 6", "GiaTri": 18 },
  { "Nhom": "DoiTuongAT", "NoiDung": "Quản lý sửa chữa lưới 7", "GiaTri": 19 },
  { "Nhom": "DoiTuongAT", "NoiDung": "Vận hành trạm biến áp", "GiaTri": 20 },
  { "Nhom": "DoiTuongAT", "NoiDung": "Quản lý HĐMBĐ", "GiaTri": 21 },
  { "Nhom": "DoiTuongAT", "NoiDung": "Dịch vụ khách hàng", "GiaTri": 22 },
  { "Nhom": "DoiTuongAT", "NoiDung": "Thu ngân viên", "GiaTri": 23 },
  { "Nhom": "DoiTuongAT", "NoiDung": "Ghi chỉ số", "GiaTri": 24 },
  { "Nhom": "DoiTuongAT", "NoiDung": "Quản lý hệ thống đo đếm", "GiaTri": 25 },
  { "Nhom": "DoiTuongAT", "NoiDung": "Quy định hệ thống đo đếm điện", "GiaTri": 26 },
  { "Nhom": "DoiTuongAT", "NoiDung": "Kỹ thuật đo lường", "GiaTri": 27 },

  { "Nhom": "TrangThaiGiaoHang", "NoiDung": "Đã thanh toán", "GiaTri": 3 },
  { "Nhom": "TrangThaiGiaoHang", "NoiDung": "Đã giao", "GiaTri": 2 },
  { "Nhom": "TrangThaiGiaoHang", "NoiDung": "Đang giao", "GiaTri": 1 },
  { "Nhom": "TrangThaiGiaoHang", "NoiDung": "Chưa giao", "GiaTri": 0 },

]

